-- 21.Lấy ra danh sách các hóa đơn gồm các thông tin: Số hóa đơn, ngày,
-- tên khách hàng, địa chỉ khách hàng, tổng trị giá của hóa đơn.
SELECT HOADON.MAHD, NGAY, TENKH, DIACHIKH, SUM(GIABAN * SL) AS TONGGIABAN
FROM dbo.HOADON, dbo.KHACHHANG, dbo.CTHD
	WHERE KHACHHANG.MAKH = HOADON.MAKH
		AND CTHD.MAHD = HOADON.MAHD
GROUP BY HOADON.MAHD, NGAY, TENKH, DIACHIKH

CREATE VIEW CAU21
AS

	SELECT MAHD, NGAY, TENKH, DIACHIKH, SUM(GIABAN * SL) AS TONGGIABAN
	FROM BangTongHop
	GROUP BY MAHD, NGAY, TENKH, DIACHIKH
GO
SELECT * FROM CAU21
-- 22.Lấy ra hóa đơn có tổng trị giá lớn nhất gồm các thông tin:
-- Số hóa đơn, ngày, tên khách hàng, địa chỉ khách hàng, tổng trị giá của hóa đơn.
SELECT TOP (1) HOADON.MAHD, NGAY, TENKH, DIACHIKH, SUM(GIABAN * SL) AS TONGGIABAN
FROM dbo.HOADON, dbo.KHACHHANG, dbo.CTHD
	WHERE KHACHHANG.MAKH = HOADON.MAKH
		AND CTHD.MAHD = HOADON.MAHD
GROUP BY HOADON.MAHD, NGAY, TENKH, DIACHIKH
ORDER BY TONGGIABAN DESC

SELECT TOP(1) MAHD, NGAY, TENKH, DIACHIKH, SUM(GIABAN * SL) AS TONGGIABAN
FROM BangTongHop
GROUP BY MAHD, NGAY, TENKH, DIACHIKH
ORDER BY TONGGIABAN DESC

SELECT MAHD, NGAY, TENKH, DIACHIKH, TONGGIABAN
FROM CAU21
WHERE TONGGIABAN = (SELECT MAX(TONGGIABAN) FROM CAU21)
-- 23.Lấy ra hóa đơn có tổng trị giá lớn nhất trong tháng 5/2010 gồm
-- các thông tin: Số hóa đơn, ngày, tên khách hàng, địa chỉ khách hàng, tổng trị giá của hóa đơn.
SELECT MAHD, NGAY, TENKH, DIACHIKH, TONGGIABAN
FROM CAU21
WHERE TONGGIABAN =
(
	SELECT MAX(TONGGIABAN) FROM CAU21
	WHERE YEAR(NGAY) = 2010 AND MONTH(NGAY) = 5
)
-- 24.Đếm xem mỗi khách hàng có bao nhiêu hóa đơn.
CREATE VIEW CAU24
AS
	SELECT TENKH, COUNT(MAHD) AS [SOLUONGHOADON]
	FROM dbo.KHACHHANG, dbo.HOADON
	WHERE KHACHHANG.MAKH = HOADON.MAKH
	GROUP BY TENKH
GO
SELECT * FROM CAU24
-- 25.Đếm xem mỗi khách hàng, mỗi tháng có bao nhiêu hóa đơn.
SELECT TENKH, MONTH(NGAY) AS THANG, COUNT(MAHD) AS [SOLUONGHOADON]
FROM dbo.KHACHHANG, dbo.HOADON
WHERE KHACHHANG.MAKH = HOADON.MAKH
GROUP BY TENKH, MONTH(NGAY)
-- 26.Lấy ra các thông tin của khách hàng có số lượng hóa đơn mua hàng nhiều nhất.
CREATE VIEW TONGSOLUONGHOADON
AS
	SELECT KHACHHANG.MAKH, COUNT(MAHD) AS [SOLUONGHOADON]
		FROM dbo.KHACHHANG, dbo.HOADON
		WHERE KHACHHANG.MAKH = HOADON.MAKH
		GROUP BY KHACHHANG.MAKH
GO
SELECT * FROM TONGSOLUONGHOADON

SELECT *
FROM dbo.KHACHHANG
WHERE MAKH = (
	SELECT MAKH FROM TONGSOLUONGHOADON WHERE SOLUONGHOADON =
		(SELECT MAX(SOLUONGHOADON) FROM TONGSOLUONGHOADON))
-- 27.Lấy ra các thông tin của khách hàng có số lượng hàng mua nhiều nhất.
DROP VIEW TONGSLHANGHOA
CREATE VIEW TONGSLHANGHOA
AS
	SELECT
			KHACHHANG.MAKH, SUM(SL) AS SLHANGHOA
		FROM dbo.HOADON, dbo.KHACHHANG, dbo.VATTU, dbo.CTHD
		WHERE KHACHHANG.MAKH = HOADON.MAKH
			AND CTHD.MAHD = HOADON.MAHD
			AND CTHD.MAVT = VATTU.MAVT
		GROUP BY KHACHHANG.MAKH
GO
SELECT * FROM TONGSLHANGHOA

SELECT *
FROM dbo.KHACHHANG
WHERE MAKH = (
		SELECT MAKH
FROM TONGSLHANGHOA
WHERE SLHANGHOA = (SELECT MAX(SLHANGHOA)
FROM TONGSLHANGHOA)
		)
-- 28.Lấy ra các thông tin về các mặt hàng mà được bán trong nhiều hóa đơn nhất.

CREATE VIEW BangTongHopVatTu
AS
	SELECT VATTU.MAVT, HOADON.MAHD, SL
	FROM dbo.HOADON, dbo.KHACHHANG, dbo.VATTU, dbo.CTHD
	WHERE KHACHHANG.MAKH = HOADON.MAKH
		AND CTHD.MAHD = HOADON.MAHD
		AND CTHD.MAVT = VATTU.MAVT
GO
SELECT * FROM BangTongHopVatTu

CREATE VIEW SLVATTU_HD
AS
	SELECT MAVT, COUNT(MAHD) AS SLHOADON
	FROM BangTongHopVatTu
	GROUP BY MAVT
GO

SELECT *
FROM dbo.VATTU
WHERE MAVT in
(SELECT MAVT
FROM SLVATTU_HD
WHERE SLHOADON = (SELECT MAX(SLHOADON)
FROM SLVATTU_HD))
-- 29.Lấy ra các thông tin về các mặt hàng mà được bán nhiều nhất.
CREATE VIEW VTBANNHIEUNHAT
AS
	SELECT TOP(1) MAVT, SUM(SL) AS TONGSLBAN FROM BangTongHopVatTu
	GROUP BY MAVT
	ORDER BY TONGSLBAN DESC
GO
SELECT * FROM dbo.VATTU WHERE MAVT = (SELECT MAVT FROM VTBANNHIEUNHAT)
-- 30.Lấy ra danh sách tất cả các khách hàng gồm Mã khách hàng,
-- tên khách hàng, địa chỉ, số lượng hóa đơn đã mua
-- (nếu khách hàng đó chưa mua hàng thì cột số lượng hóa đơn để trống)
SELECT KHACHHANG.MAKH, TENKH, SLHOADON =
	CASE  
		WHEN COUNT(HOADON.MAHD) != 0 THEN COUNT(HOADON.MAHD)
		ELSE NULL
	END
FROM dbo.KHACHHANG LEFT JOIN dbo.HOADON ON
KHACHHANG.MAKH = HOADON.MAKH
GROUP BY KHACHHANG.MAKH, TENKH